# Generated by Django 2.2.5 on 2022-01-13 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('email_active', models.BooleanField(default=False, verbose_name='邮箱验证状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用戶资料表',
                'verbose_name_plural': '用戶资料表',
                'db_table': 'tb_users_profile',
            },
        ),
    ]
