# Generated by Django 2.2.5 on 2022-01-13 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0002_auto_20220110_0549'),
        ('users', '0002_auto_20220113_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建数据的时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新数据的时间')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('cover', models.TextField(verbose_name='封面')),
                ('status', models.SmallIntegerField(choices=[(1, 'DRAFT'), (2, 'UNREVIEWED'), (3, 'APPROVED'), (4, 'FAILED'), (5, 'DELETED'), (6, 'BANNED')], default=1, verbose_name='文章状态')),
                ('reason', models.CharField(max_length=256, verbose_name='未通过原因')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='点踩数')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='area.Area', verbose_name='地区ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='users.User', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '文章基本信息表',
                'verbose_name_plural': '文章基本信息表',
                'db_table': 'tb_article',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建数据的时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新数据的时间')),
                ('name', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'tb_category',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建数据的时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新数据的时间')),
                ('content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回复数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='文章id')),
                ('comment_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_subs', to='articles.Comment', verbose_name='父评论')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '文章评论表',
                'verbose_name_plural': '文章评论表',
                'db_table': 'tb_aticle_comment',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='文章id')),
                ('article_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='评论id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '文章评论表',
                'verbose_name_plural': '文章评论表',
                'db_table': 'tb_like_comment',
            },
        ),
        migrations.CreateModel(
            name='DislikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='文章id')),
                ('article_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Comment', verbose_name='评论id')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '文章评论表',
                'verbose_name_plural': '文章评论表',
                'db_table': 'tb_dislike_comment',
            },
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='帖文内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='文章ID')),
            ],
            options={
                'verbose_name': '文章内容表',
                'verbose_name_plural': '文章内容表',
                'db_table': 'tb_aticle_content',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Category', verbose_name='分类ID'),
        ),
    ]
