# Generated by Django 2.2.5 on 2022-01-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='tab_citys',
        ),
    ]
